services:
  nginx:
    command:
      - nginx
      - -g
      - daemon off;
    container_name: http-captive-portal
    entrypoint:
      - /docker-entrypoint.sh
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    ports:
      - 80:80
      - 443:443
    image: docker.io/nginx:alpine
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl:ro
    restart: unless-stopped
